name: unsigned_release
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
on:
  push:
    branches:
    - custom-zed
jobs:
  bundle_linux_x86_64:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
    - name: steps::checkout_repo
      uses: actions/checkout@v4
      with:
        clean: false
    - name: steps::setup_linux
      run: ./script/linux
    - name: steps::install_mold
      run: ./script/install-mold
    - name: steps::download_wasi_sdk
      run: ./script/download-wasi-sdk
    - name: steps::setup_node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: steps::bundle_linux
      run: ./script/bundle-linux
    - name: '@actions/upload-artifact zed-linux-x86_64.tar.gz'
      uses: actions/upload-artifact@v4
      with:
        name: zed-linux-x86_64.tar.gz
        path: target/release/zed-linux-x86_64.tar.gz
        if-no-files-found: error
        retention-days: 90
    - name: '@actions/upload-artifact zed-remote-server-linux-x86_64.gz'
      uses: actions/upload-artifact@v4
      with:
        name: zed-remote-server-linux-x86_64.gz
        path: target/zed-remote-server-linux-x86_64.gz
        if-no-files-found: error
        retention-days: 90
    - name: steps::run_info
      run: |
        echo "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "Run ID: ${{ github.run_id }}"
